# Generated by Django 2.1.8 on 2020-07-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortUrl', models.CharField(max_length=20)),
                ('longUrl', models.CharField(max_length=200)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
